# Generated by Django 5.2.11 on 2026-04-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='ConfiguracionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.TimeField()),
                ('dias_laborales', models.ManyToManyField(blank=True, to='core.diasemana')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_laboral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones Laborales',
            },
        ),
    ]
