# Generated by Django 5.2.11 on 2026-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_configuracionlaboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionlaboral',
            name='horario_entrada',
        ),
        migrations.RemoveField(
            model_name='configuracionlaboral',
            name='horario_salida',
        ),
        migrations.AddField(
            model_name='configuracionlaboral',
            name='turno_preferido',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Indiferente', 'Indiferente')], default='Indiferente', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionlaboral',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
