# Generated by Django 5.2.11 on 2026-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Días de la Semana',
                'ordering': ['orden'],
            },
        ),
    ]
