# Generated by Django 5.2.11 on 2026-04-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_initial'),
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monto_horas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_plus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_adelantos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ajustes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='empresa.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-periodo_anio', '-periodo_mes', 'empleado__nombre'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLUS', 'Plus'), ('DESCUENTO', 'Descuento'), ('ADELANTO', 'Adelanto'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='sueldos.liquidacion')),
            ],
            options={
                'verbose_name_plural': 'Conceptos en Liquidaciones',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalleHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.horario')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_horas', to='sueldos.liquidacion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Horas en Liquidaciones',
                'ordering': ['fecha'],
            },
        ),
    ]
