# Generated by Django 5.2.11 on 2026-05-01 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_horario_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['empresa', 'sucursal', 'fecha', 'hora_inicio'], 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
